pipeline {
    agent any

    stages {
        stage('Prepare') {
            steps {
                sh 'git clone https://github.com/Lauravll/UTN-DevOps.git || true'
                sh 'cd utn-devops-app && sudo git checkout unidad-4-pruebas && sudo git pull'
                sh 'cd utn-devops-app/myapp && sudo /usr/local/bin/composer install --no-scripts'
                sh 'chmod 777 ./utn-devops-app/myapp/bootstrap/cache/'
            }
        }
        stage('Build') {
            steps {
                sh 'find . -path ./utn-devops-app/myapp/vendor -prune -o -name \\*.php -exec php -l "{}" \\;'
                retry(2) {
                    sh 'cd utn-devops-app/myapp && sudo /usr/local/bin/composer install --no-scripts --prefer-dist'
                }
            }
        }
        stage('Test') {
            steps {
                sh './utn-devops-app/myapp/vendor/bin/phpunit -c ./utn-devops-app/myapp/phpunit.xml'
            }
        }
    }
}
